version: "3.0"
services:
  elasticsearch:
    container_name: elastic
    image: elasticsearch:7.4.2
    volumes:
      - es-data:/usr/share/elasticsearch/data
    environment:
      - ELASTIC_PASSWORD=elastic
      - xpack.security.enabled=true
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    networks:
      - wepaas          
    restart: always            
    ulimits:
      memlock:
        soft: -1
        hard: -1      
    ports:
      - 9200:9200
volumes:
  es-data:      
networks:
  wepaas:
    external: true    
