version: '2'

networks:
  wepaas:
    external: true

services:
  minio:
    image: 'bitnami/minio:latest'
    # ports:
    #   - '29000:9000'
    #   - '29001:9001'
    environment:
      - MINIO_ROOT_USER=root
      - MINIO_ROOT_PASSWORD=password
    networks:
      - wepaas 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minio.rule=Host(`minio.wepaas.cc`)"
      - "traefik.http.routers.minio.entrypoints=web"      
      - "traefik.http.services.minio.loadbalancer.server.port=9001"          
    volumes:
      - minio-data:/data
volumes:
  minio-data:
