version: "3"
services:
    node-exporter:
        image: bitnami/node-exporter
        container_name: node-exporter
        restart: always
        ports:
            - "9100:9100"
        volumes:
            - ./config/:/opt/bitnami/prometheus/conf/
        command:
            - '--web.config=/opt/bitnami/prometheus/conf/config.yml'