version: '3.1'
services:
  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./config/alertmanager.yml:/opt/bitnami/alertmanager/conf/config.yml
      - alertmanager-data:/opt/bitnami/data
    # ports:
    #   - 9093:9093
    networks:
      - wepaas 
    restart: always            
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alertmanager.rule=Host(`alertmanager.wepaas.cc`)"
      - "traefik.http.routers.alertmanager.entrypoints=web"      
      - "traefik.http.services.alertmanager.loadbalancer.server.port=9093"         

volumes:
  alertmanager-data:

networks:
  wepaas:
    external: true