groups:
    - name: node_cpu_seconds:sum:5min
      rules:
        - record: node_cpu_seconds:sum:5min
          expr: (1-(sum(increase(node_cpu_seconds_total{mode='idle'}[5m]))by(job,instance)) / (sum(increase(node_cpu_seconds_total[5m]))by(job,instance))) *100
        