version: '3.1'
services:
  mongo:
    image: mongo:4.2.0
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - wepaas                

volumes:
  mongo-data:

networks:
  wepaas:
    external: true    