version: '2'

networks:
  neo4j-network:
    driver: bridge

services:
  neo4j:
    image: bitnami/neo4j:latest
    environment:
      - NEO4J_PASSWORD=password

    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'
    volumes:
      - neo4j-plugins:/bitnami/neo4j/plugins   
      - neo4j-data:/bitnami   

volumes:
  neo4j-plugins:
  neo4j-data: