version: '3.8'
services:
  # elasticsearch:
  #   image: elasticsearch:7.4.2
  #   container_name: elasticsearch
  #   ports:
  #     - "9200:9200"
  #   healthcheck:
  #     test: [ "CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1" ]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 10s
  #   environment:
  #     - discovery.type=single-node
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1

  oap:
    image: apache/skywalking-oap-server
    container_name: oap
    # depends_on:
    #   elasticsearch:
    #     condition: service_healthy
    # links:
    #   - elasticsearch
    ports:
      - "11800:11800"
      - "12800:12800"
    networks:
      - wepaas             
    volumes:
      - ./config/alarm-settings.yml:/skywalking/config/alarm-settings.yml:ro
    # healthcheck:
    #   test: [ "CMD-SHELL", "/skywalking/bin/swctl ch" ]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 10s
    environment:
      SW_STORAGE: elasticsearch
      SW_STORAGE_ES_CLUSTER_NODES: elasticsearch:9200
      SW_ES_USER: elastic
      SW_ES_PASSWORD: elastic
      SW_HEALTH_CHECKER: default
      SW_TELEMETRY: prometheus
      JAVA_OPTS: "-Xms2048m -Xmx2048m"
      TZ: Asia/Shanghai

  ui:
    image: apache/skywalking-ui
    container_name: ui
    # depends_on:
    #   oap:
    #     condition: service_healthy
    links:
      - oap
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.skywalking.rule=Host(`skywalking.wepaas.cc`)"
      - "traefik.http.routers.skywalking.entrypoints=web"      
      - "traefik.http.services.skywalking.loadbalancer.server.port=8080"            
    # ports:
    #   - "38080:8080"
    networks:
      - wepaas             
    environment:
      SW_OAP_ADDRESS: http://oap:12800
      TZ: Asia/Shanghai

networks:
  wepaas:
    external: true    