version: '3.1'
services:
  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./config/alertmanager.yml:/opt/bitnami/alertmanager/conf/config.yml
      - alertmanager-data:/opt/bitnami/data
    ports:
      - 9093:9093

volumes:
  alertmanager-data: