version: '3.1'
services:
    coredns:
        image: coredns/coredns
        container_name: coredns
        restart: always
        expose:
            - '53'
            - '53/udp'
        networks:
        - wepaas               
        ports:
            - '53:53'
            - '53:53/udp'
        volumes:
            - './config:/etc/coredns'
        command: -conf /etc/coredns/corefile
networks:
  wepaas:
    external: true              