version: "3.0"
services:
  elasticsearch:
    container_name: elastic
    image: elasticsearch:7.17.6
    volumes:
      - es-data:/usr/share/elasticsearch/data
    environment:
      - ELASTIC_PASSWORD=elastic
      - xpack.security.enabled=true
      - "discovery.type=single-node"
    ulimits:
      memlock:
        soft: -1
        hard: -1      
    ports:
      - 9200:9200
volumes:
  es-data:      