version: '2'

services:
  consul:
    image: bitnami/consul:latest
    ports:
      - '8300:8300'
      - '8301:8301'
      - '8301:8301/udp'
      - '8500:8500'
      - '8600:8600'
      - '8600:8600/udp'
    volumes:
      - consul-data:/bitnami

volumes:
  consul-data:    
