version: "3"
services:
    loki:
      image: grafana/loki
      ports:
        - "3100:3100"
      restart: always                
      networks:
        - wepaas   
      volumes:
          - loki-storage:/loki
volumes:
  loki-storage:

networks:
  wepaas:
    external: true