version: '3'
services:
  grafana-agent:
    image: grafana/agent:latest
    volumes:
      - ./config/agent.yml:/etc/agent/agent.yaml
      - grafana-agent-data:/etc/agent/data
    networks:
      - wepaas       

volumes:
  grafana-agent-data:


networks:
  wepaas:
    external: true