version: '3.8'
services:
  datainsight:
    image: ccr.ccs.tencentyun.com/megalab/datainsight
    extra_hosts:
      datainsight.wepaas.cc: 10.11.25.50
    networks:
      - wepaas       
    restart: always            
    container_name: datainsight
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.datainsight.rule=Host(`datainsight.wepaas.cc`)"
      - "traefik.http.routers.datainsight.entrypoints=web"      
      - "traefik.http.services.datainsight.loadbalancer.server.port=9000"        
    ports:
      - 20001:9000
    volumes:
      - ${PWD}/configs/graylog.conf:/products/graylog.conf:ro
networks:
  wepaas:
    external: true      
