version: '2'
services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    restart: always
    volumes:
      - zookeeper-data:/data
    networks:
      - wepaas         
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    networks:
      - wepaas         
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.11.25.50
      KAFKA_MESSAGE_MAX_BYTES: 2000000
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - kafka-data:/kafka

volumes:
  zookeeper-data:
  kafka-data:


networks:
  wepaas:
    external: true