modules:
  http_2xx:
    prober: http
    http:
      method: GET
      preferred_ip_protocol: "ip4"
  http_post_2xx:
    prober: http
    http:
      method: POST
      preferred_ip_protocol: "ip4"
  tcp:
    prober: tcp
  ping:
    prober: icmp
    timeout: 3s
    icmp:
      preferred_ip_protocol: "ip4"