version: '3'
services:
  prometheus:
    image: bitnami/prometheus
    volumes:
      - prometheus-data:/opt/bitnami/prometheus/data
      - ./config/:/opt/bitnami/prometheus/conf/
    networks:
      - mega-ops
    ports:
      - 9090:9090
    command:
      - '--config.file=/opt/bitnami/prometheus/conf/prometheus.yml'
      - '--storage.tsdb.retention.time=10d'
      - '--storage.tsdb.retention.size=1GB'
      - '--web.enable-admin-api'
      - '--web.enable-lifecycle'
      
volumes:
  prometheus-data:

networks:
  mega-ops: